Update Dependencies
jsynowiec/good-sentry pull request #3
Opened 2017-05-30 18:56 UTC by MatthewCallis

Update Dependencies

[raven v1.1.1 ➜ v2.0.2](https://github.com/getsentry/raven-js/blob/master/CHANGELOG.md)
babel-cli  v6.18.0 ➜ v6.24.1
babel-core v6.21.0 ➜ 6.24.1
babel-eslint v7.1.0 ➜ v7.2.3
babel-jest v18.0.0 ➜ v20.0.3
babel-preset-es2015 v6.28.0 ➜ v6.24.1
[eslint v3.13.1 ➜ v3.19.0](https://github.com/eslint/eslint/blob/master/CHANGELOG.md)
eslint-config-airbnb-base v11.0.1 ➜ v11.2.0
eslint-plugin-import v2.2.0 ➜ v2.3.0
[jest v18.1.0 ➜ v20.0.4](https://github.com/facebook/jest/blob/master/CHANGELOG.md)

2017-06-05 08:15 UTC, jsynowiec requested changes
Thanks for contribution!

2017-06-05 08:15 UTC, jsynowiec commented on package.json
> +    "raven": "~2.0.2"
Can you please split this into two separate commits? One with dev dependencies and the other with production ones.

( Personally I like to keep packages grouped while updating, e.g. bump babel-* versions, test and commit, then other packages. It's easier to verify and revert if there are problems. )

2017-06-05 18:06 UTC, MatthewCallis commented
@jsynowiec I split the commits up, 👍🏼

2017-06-05 23:58 UTC, MatthewCallis commented on package.json
> +    "raven": "~2.0.2"
Done!

2017-06-07 09:01 UTC, jsynowiec approved these changes

2017-06-07 09:02 UTC, merged